/**:
  ros__parameters:
    map_frame: world
    resolution: 0.1
    width: 400
    height: 400
    origin_x: -20.0
    origin_y: -20.0
    max_range: 6.0
    update_rate: 2.0
    frontier_min_size: 10
    selection_mode: score
    goal_hysteresis_distance: 0.20
    goal_hold_sec: 1.2
    goal_reselect_distance: 0.7
    max_goal_distance: 4.0
    min_goal_distance: 0.8
    min_forward_cos: -0.35
    forward_score_gain: 0.8
    backward_penalty: 0.35
    obstacle_clearance_cells: 6
    goal_standoff_distance: 0.8
    goal_standoff_search_radius: 1.4
    startup_delay: 12.0
    force_replan_min_score_gain: 0.0
    force_replan_min_goal_separation: 0.25
